FORT = gfortran-12
#FORT = x86_64-w64-mingw32-gfortran-win32

OPTC = O2

algen_dir = ../TOOLIB/ALGEN
chole_dir = ../TOOLIB/CHOLE
digis_dir = ../TOOLIB/DIGIS
fftw3_dir = ../TOOLIB/FFTW3
files_dir = ../TOOLIB/FILES
gplot_dir = ../TOOLIB/GPLOT
intpl_dir = ../TOOLIB/INTPL
least_dir = ../TOOLIB/LEAST
minim_dir = ../TOOLIB/MINIM
msolv_dir = ../TOOLIB/MSOLV
qsort_dir = ../TOOLIB/QSORT
randm_dir = ../TOOLIB/RANDM
splin_dir = ../TOOLIB/SPLIN
tchev_dir = ../TOOLIB/TCHEV
utils_dir = ../TOOLIB/UTILS

abbot_dir = ../TPGLIB/ABBOT
aniso_dir = ../TPGLIB/ANISO
asfc2_dir = ../TPGLIB/ASFC2
filtr_dir = ../TPGLIB/FILTR
deriv_dir = ../TPGLIB/DERIV
morph_dir = ../TPGLIB/MORPH
stats_dir = ../TPGLIB/STATS

